In [101]:
import sympy as sp

In [144]:
# sigma = sp.Symbol('s')
sigma = sp.Symbol('s')
# sigma = 1
t = sp.Symbol('t')
x,v = sp.Symbol('x'), sp.Symbol('v')
z = sp.Matrix([x,v])
exp_2t = sp.exp(2*t)
sig_t = sp.Matrix([[(2*t**2 - 2 * t + 1) * exp_2t - 1, - 2 * t**2 * exp_2t],
                   [- 2 * t**2 * exp_2t, (2*t**2 + 2 * t + 1) * exp_2t - 1]])
exp_At = sp.exp(-t) * sp.Matrix([[t + 1, t],
                                 [-t, 1 - t]])

In [187]:
sig_t

Matrix([
[(2*t**2 - 2*t + 1)*exp(2*t) - 1,                -2*t**2*exp(2*t)],
[               -2*t**2*exp(2*t), (2*t**2 + 2*t + 1)*exp(2*t) - 1]])

In [162]:
var_t = sp.simplify(exp_At * sig_t * exp_At.T)
var_t


Matrix([
[(-2*t**2 - 2*t + exp(2*t) - 1)*exp(-2*t),                         2*t**2*exp(-2*t)],
[                        2*t**2*exp(-2*t), (-2*t**2 + 2*t + exp(2*t) - 1)*exp(-2*t)]])

In [148]:
score_mat = sp.simplify(exp_At * (sigma**2 * sp.eye(2) + sig_t) * exp_At.T)

ValueError: Matrix must be Hermitian.

In [ ]:
a = sp.Symbol('a')
b = sp.Symbol('b')
c = sp.Symbol('c')
d = sp.Symbol('d')

c_in = sp.Matrix([[a,0],[c,d]])

sp.simplify(c_in * score_mat * c_in.T)
sp.solve(c_in * score_mat * c_in.T - sp.eye(2), (a,b,c,d))

In [106]:
inv = sp.simplify(score_mat.inv())
inv

Matrix([
[(2*s**2*t**2 - 2*s**2*t + s**2 - 2*t**2 + 2*t + exp(2*t) - 1)*exp(2*t)/(s**4 + 4*s**2*t**2*exp(2*t) + 2*s**2*exp(2*t) - 2*s**2 - 4*t**2*exp(2*t) + exp(4*t) - 2*exp(2*t) + 1),                                             2*t**2*(s**2 - 1)*exp(2*t)/(s**4 + 4*s**2*t**2*exp(2*t) + 2*s**2*exp(2*t) - 2*s**2 - 4*t**2*exp(2*t) + exp(4*t) - 2*exp(2*t) + 1)],
[                                                                     2*t**2*(s**2 - 1)*exp(2*t)/(s**4 - 2*s**2 + (4*s**2*t**2 + 2*s**2 - 4*t**2 + exp(2*t) - 2)*exp(2*t) + 1), (2*s**2*t**2 + 2*s**2*t + s**2 - 2*t**2 - 2*t + exp(2*t) - 1)*exp(2*t)/(s**4 + 4*s**2*t**2*exp(2*t) + 2*s**2*exp(2*t) - 2*s**2 - 4*t**2*exp(2*t) + exp(4*t) - 2*exp(2*t) + 1)]])

In [107]:
score = -sp.simplify(inv * z)
score

Matrix([
[             -(2*t**2*v*(s**2 - 1) + x*(2*s**2*t**2 - 2*s**2*t + s**2 - 2*t**2 + 2*t + exp(2*t) - 1))*exp(2*t)/(s**4 + 4*s**2*t**2*exp(2*t) + 2*s**2*exp(2*t) - 2*s**2 - 4*t**2*exp(2*t) + exp(4*t) - 2*exp(2*t) + 1)],
[-(2*s**2*t**2*v + 2*s**2*t**2*x + 2*s**2*t*v + s**2*v - 2*t**2*v - 2*t**2*x - 2*t*v + v*exp(2*t) - v)*exp(2*t)/(s**4 + 4*s**2*t**2*exp(2*t) + 2*s**2*exp(2*t) - 2*s**2 - 4*t**2*exp(2*t) + exp(4*t) - 2*exp(2*t) + 1)]])

In [108]:
score[0]

-(2*t**2*v*(s**2 - 1) + x*(2*s**2*t**2 - 2*s**2*t + s**2 - 2*t**2 + 2*t + exp(2*t) - 1))*exp(2*t)/(s**4 + 4*s**2*t**2*exp(2*t) + 2*s**2*exp(2*t) - 2*s**2 - 4*t**2*exp(2*t) + exp(4*t) - 2*exp(2*t) + 1)

In [109]:
partial_t = sp.simplify(sp.diff(score, t))
partial_t

Matrix([
[2*(2*(2*t**2*v*(s**2 - 1) + x*(2*s**2*t**2 - 2*s**2*t + s**2 - 2*t**2 + 2*t + exp(2*t) - 1))*(2*s**2*t**2 + 2*s**2*t + s**2 - 2*t**2 - 2*t + exp(2*t) - 1)*exp(2*t) - (2*t**2*v*(s**2 - 1) + 2*t*v*(s**2 - 1) + x*(2*s**2*t - s**2 - 2*t + exp(2*t) + 1) + x*(2*s**2*t**2 - 2*s**2*t + s**2 - 2*t**2 + 2*t + exp(2*t) - 1))*(s**4 + 4*s**2*t**2*exp(2*t) + 2*s**2*exp(2*t) - 2*s**2 - 4*t**2*exp(2*t) + exp(4*t) - 2*exp(2*t) + 1))*exp(2*t)/(s**4 + 4*s**2*t**2*exp(2*t) + 2*s**2*exp(2*t) - 2*s**2 - 4*t**2*exp(2*t) + exp(4*t) - 2*exp(2*t) + 1)**2],
[                            4*((2*s**2*t**2 + 2*s**2*t + s**2 - 2*t**2 - 2*t + exp(2*t) - 1)*(2*s**2*t**2*v + 2*s**2*t**2*x + 2*s**2*t*v + s**2*v - 2*t**2*v - 2*t**2*x - 2*t*v + v*exp(2*t) - v)*exp(2*t) + (s**4 + 4*s**2*t**2*exp(2*t) + 2*s**2*exp(2*t) - 2*s**2 - 4*t**2*exp(2*t) + exp(4*t) - 2*exp(2*t) + 1)*(-s**2*t**2*v - s**2*t**2*x - 2*s**2*t*v - s**2*t*x - s**2*v + t**2*v + t**2*x + 2*t*v + t*x - v*exp(2*t) + v))*exp(2*t)/(s**4 + 4*s**2*t**2*exp

In [110]:
sx, sv = score[0], score[1]

f = sp.simplify(2 * sp.diff(sv, v) + 2 * sv**2 - v * sx + (x + 2 * v) * sv + 2)
f

(2*(s**4 + 4*s**2*t**2*exp(2*t) + 2*s**2*exp(2*t) - 2*s**2 - 4*t**2*exp(2*t) + exp(4*t) - 2*exp(2*t) + 1)**2 + (s**4 + 4*s**2*t**2*exp(2*t) + 2*s**2*exp(2*t) - 2*s**2 - 4*t**2*exp(2*t) + exp(4*t) - 2*exp(2*t) + 1)*(-4*s**2*t**2 - 4*s**2*t - 2*s**2 + 4*t**2 + 4*t + v*(2*t**2*v*(s**2 - 1) + x*(2*s**2*t**2 - 2*s**2*t + s**2 - 2*t**2 + 2*t + exp(2*t) - 1)) - (2*v + x)*(2*s**2*t**2*v + 2*s**2*t**2*x + 2*s**2*t*v + s**2*v - 2*t**2*v - 2*t**2*x - 2*t*v + v*exp(2*t) - v) - 2*exp(2*t) + 2)*exp(2*t) + 2*(2*s**2*t**2*v + 2*s**2*t**2*x + 2*s**2*t*v + s**2*v - 2*t**2*v - 2*t**2*x - 2*t*v + v*exp(2*t) - v)**2*exp(4*t))/(s**4 + 4*s**2*t**2*exp(2*t) + 2*s**2*exp(2*t) - 2*s**2 - 4*t**2*exp(2*t) + exp(4*t) - 2*exp(2*t) + 1)**2

In [111]:
grad_x, grad_v = sp.simplify(sp.diff(f,x)), sp.simplify(sp.diff(f,v))


In [112]:
partial_t[0] == grad_x
partial_t[1] == grad_v

a = sp.simplify(partial_t[0] - grad_x)
b = sp.simplify(partial_t[1] - grad_v)

a

0

In [113]:
b

0

In [156]:
a = sp.Symbol('a')
b = sp.Symbol('b')
c = sp.Symbol('c')
d = sp.Symbol('d')

A = sp.Matrix([[a,b],[b,d]])
A.cholesky(hermitian=False)

Matrix([
[  sqrt(a),                0],
[b/sqrt(a), sqrt(d - b**2/a)]])

In [196]:
from utils.sde_lib import CLD
import torch
import numpy as np

sde = CLD()

t = torch.tensor([sde.delta])
a,b,c,d = sde.marginal_prob_var_components(t)
a,b,c,d = sde.get_exp_At_components(t)
xx,xv,vv = sde.get_sig_components(t)

mat1 = np.array([[a.item(),b.item()],
                 [c.item(),d.item()]])
mat2 = np.array(([xx.item(), xv.item()],
                 [xv.item(), vv.item()]))

b = sde.beta_int(t)
print(b)
print(torch.exp(2*b))
print((2 * b**2 - 2 * b + 1))
print(((2 * b**2 - 2 * b + 1) * torch.exp(2*b)).item())
print(mat1)
print(mat2)
print(mat1 @ mat2 @ mat1.T)
# print(f'{sde.delta : .3f} {sde.marginal_prob_std(torch.tensor([sde.delta]))}')

tensor([5.4975e-05])
tensor([1.0001])
tensor([0.9999])
0.9999999403953552
[[ 1.00000000e+00  5.49719844e-05]
 [-5.49719844e-05  9.99890089e-01]]
[[-5.96046448e-08 -6.04516659e-09]
 [-6.04516659e-09  2.19821930e-04]]
[[-5.96046451e-08  6.04149397e-09]
 [ 6.04149397e-09  2.19773612e-04]]
